### ISSUE TITLE
Product

### ISSUE THREAD

**Issue by d-jo** [Emergen-SEE/Emergen-SEE-Situations#10]
It is not clear to me if the product exists as an app, key-fob, or both. The README describes an app, but in the value proposition, a key fob is mentioned. Maybe include a section that describes the potential benefits for each option, and what customer segments would benefit from them.

Declan

**Comment by tylerDavisUno** [comment]
I think that it would also be a good idea to have multiple types of physical accessories. Key fob, necklace, etc. so there are multiple ways to interact with the app.
