### ISSUE TITLE
Crowded Market already

### ISSUE THREAD

**Issue by mattross1** [Emergen-SEE/Emergen-SEE-Situations#16]
This product in theory is a great idea but there are many others out there that do the same thing and are already established. If the defining feature of your product is that it uses cellular service, won't the larger companies, if they aren't already doing it, take this idea and more easily integrate it with there already established service? Your customer segment makes since but there are products already marketed to each of them. You mention that you know there are products that already do this, but you also say yours is different because of the button.
"helps people to reach out for help in case of an emergency. There are many other companies that provide this service, but our service is unique in different ways. We created a button type device that will attach to your keychain and always in hand in case you need to call for help within seconds"
https://www.google.com/search?q=emergency+button

**Comment by manizha83** [comment]
Yes, it is actually a small portable button that you can attach to your key chain and always available with you, as you always carry your keys with you. It is going to have GPS tracker in it. If you don't have your phone on you, or your phone died it can still send a location. I currently do not know of a company who does provide this specific product.
